#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Set DPI. User may want to use a larger number for larger screens.
if xrandr --listmonitors | grep "Monitors: 1" ; then
  xrandr --dpi 120 &
  sed -i 's/Xft\.dpi.*$/Xft\.dpi\: 120/' "$HOME/.config/x11/xresources"
else
  xrandr --dpi 96 &
  pidof -s monitor_setup.sh || setsid -f monitor_setup.sh
  sed -i 's/Xft\.dpi.*$/Xft\.dpi\: 96/' "$HOME/.config/x11/xresources"
fi
# set the background with the `setbg` script
setbg &
# Uncomment to use Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
# Speed xrate up
xset r rate 300 50 &
# Start tmux empty tmux sesion to speed up terminal start time
tmux new-session -s server -d &
# Create mpvSockets tmp dir
[ ! -d /tmp/mpvSockets ] && mkdir /tmp/mpvSockets &

autostart="mpd remaps xcompmgr dunst unclutter /usr/lib/xdg-desktop-portal-kde sxhkd"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
# pidof -s runit &&
# 	! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
