#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 120	# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
xset r rate 300 50 &	# Speed xrate up
tmux new-session -s server -d &   # Start tmux empty tmux sesion to speed up terminal start time

autostart="mpd remaps xcompmgr dunst unclutter /usr/lib/xdg-desktop-portal-kde"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
#mpd &			# music player daemon-you might prefer it as a service though
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#xcompmgr &		# xcompmgr for transparency
#dunst &			# dunst for notifications
#unclutter &		# Remove mouse when idle
#(sleep 1 && renew-dwm) &
#/usr/lib/xdg-desktop-portal-kde &
