#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Set DPI. User may want to use a larger number for larger screens.
if xrandr --listmonitors | grep "Monitors: 1"; then
  xrandr --dpi 120 &
  sed -i 's/Xft\.dpi.*$/Xft\.dpi\: 120/' "$HOME/.config/x11/xresources"
else
  xrandr --dpi 96 &
  pidof -s monitor_setup.sh || setsid -f monitor_setup.sh
  sed -i 's/Xft\.dpi.*$/Xft\.dpi\: 96/' "$HOME/.config/x11/xresources"
fi
# set the background with the `setbg` script
setbg &
# Uncomment to use Xresources colors/settings on startup
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &
xrdbpid=$!
# Speed xrate up
xset r rate 300 50 &
# Start tmux empty tmux sesion to speed up terminal start time
while pidof tmux >/dev/null 2>&1; do
    pkill tmux
done
tmux new-session -s x-server -d &
# # Start emacs
# emacs --daemon &
# Create mpc tmp dir
[ ! -d "${MPC_TMP_DIR:-/tmp/mpc}" ] && {
    mkdir "${MPC_TMP_DIR:-/tmp/mpc}" && chmod 700 "${MPC_TMP_DIR:-/tmp/mpc}"
} &

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    # shellcheck source=/dev/null
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setsid -f unclutter --ignore-scrolling

# autostart="mpd remaps xcompmgr dunst unclutter"
# autostart="mpd remaps dunst"
autostart="mpd remaps dunst dwmblocks"

for program in $autostart; do
  pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
